.MODEL SMALL
.STACK 100H
.DATA
ARR DB 10,13,'ENTER 10 VALUES: $'
ARR1 DB 10,13,'SORTED: $'
ARRAY DB 10 DUP(0)
.CODE
MAIN PROC 
MOV AX,@DATA     ;MOVING DATA TO AX 16-BIT REGISTER
MOV DS,AX

MOV AH,9         ;PRINTING STRING
MOV DL, 20H     ;ASCII FOR SPACE
MOV DX,OFFSET ARR ;MOVING OFFSET OF ARR TO DX
INT 21H

MOV CX,10        ;MOVING COUNT OF NUMBERS ENTERED
MOV BX,OFFSET ARRAY ;MOVING ADDRESS OF ARRAY TO BX
MOV AH,1         ;INPUT SINGLE CHARACTER

INPUT:
INT 21H
MOV [BX],AL    ;MOVING THE VALUES ENTERED TO ARRAY
INC BX         ;MOVING ONTO NEXT PLACE IN ARRAY
LOOP INPUT

MOV CX,10      ;TAKING INPUT TILL CX!=0
DEC CX         ;CX = CX-1

NEXT:
MOV BX,CX
MOV SI,0    ;SI = 0

NEXTCOMP:
MOV AL,ARRAY[SI]   ;TAKING FIRST VALUE
MOV DL,ARRAY[SI+1] ;TAKING NEXT VALUE
CMP AL,DL          ;COMPARING BOTH

JC NO_SWAP         ;JUMP IF CARRY |CF=1|

MOV ARRAY[SI],DL    ;SWAPPING
MOV ARRAY[SI+1],AL

NO_SWAP:            ;IF NO SWAPPING THEN
INC SI
DEC BX
JNZ NEXTCOMP        ;JUMP IF NOT EQUAL TO ZERO

LOOP NEXT         ;LOOP LABEL

MOV AH,9          ;PRINT STRING
LEA DX,ARR1       ;MOVING OFFSET OF ARR1 TO DX
INT 21H

MOV CX,10
MOV BX,OFFSET ARRAY  ;MOVING OFFSET OF ARRAY TO BX

PRINT:      ;PRINT LABEL
MOV AH,2    ;PRINTING CHRACTER
MOV DL,[BX]   ;MOVING FIRST VALUE OF ARRAY TO DL
INT 21H      ;PRINTING THAT FIRST VALUE AFTER SORTING
INC BX       ;MOVING ONTO NEXT VALUE
LOOP PRINT   ;LOOPING TILL CX != 0

MOV AH,4CH   ;RETURNING CONTROL BACK TO DOS
INT 21H

MAIN ENDP
END MAIN